// Builds the pane's "Powered by Trusplex Operator" badge as terminal cells,
// after the Trusplex design system's Badge component (dark ground): a stadium
// pill with a violet → bayside-blue → blue gradient ring, an ebony fill with a
// violet wash that fades out before the name, the emblem, the verb in smoke
// and the name in white. Writes hooks/badge-cells.ts.
//
//   node dev/make-badge.mjs            (needs Playwright's Chromium for the emblem)
import { execFileSync } from 'node:child_process'
import { writeFileSync } from 'node:fs'

const VERB = 'Powered by'
const NAME = 'Trusplex Operator'
const ROWS = 5
const EMBLEM = JSON.parse(
  execFileSync(process.execPath, [new URL('./emblem-cells.mjs', import.meta.url).pathname, '6', '3', 'quad'], { encoding: 'utf8' }),
)
const EBONY = [0x0b, 0x0b, 0x1b], VIOLET = [0x74, 0x6d, 0xf8], BAYSIDE = [0x1c, 0x83, 0xea], BLUE = [0x00, 0x39, 0xd8]
const SMOKE = 0xd3d6e0, WHITE = 0xffffff, DEFAULT = 0x01000000
const mix = (a, b, t) => a.map((v, i) => v + (b[i] - v) * t)
const hex = c => (Math.round(c[0]) << 16) | (Math.round(c[1]) << 8) | Math.round(c[2])

// columns: cap, emblem, gap, verb, space, name, pad, cap
const R = ROWS // stadium radius in cell widths: half the height (rows are two widths tall)
const LEFT_PAD = 3, GAP = 2, RIGHT_PAD = 3
const emblemAt = LEFT_PAD
const verbAt = emblemAt + EMBLEM[0].length + GAP
const nameAt = verbAt + VERB.length + 1
const COLS = nameAt + NAME.length + RIGHT_PAD + 1
const textRow = Math.floor(ROWS / 2)

const ringAt = x => {
  const t = Math.min(1, Math.max(0, x / COLS)) // violet → bayside 55% → blue
  return t < 0.55 ? mix(VIOLET, BAYSIDE, t / 0.55) : mix(BAYSIDE, BLUE, (t - 0.55) / 0.45)
}
const fillAt = x => {
  const wash = Math.max(0, 1 - x / (nameAt - 1)) * 0.28 // fades out before the name
  return mix(EBONY, VIOLET, wash)
}
// Signed distance to a stadium spanning [0,COLS] x [0,2*ROWS] in width units (y doubled: rows are 2 tall).
const H = ROWS * 2, rad = H / 2
function sd(x, y) {
  const cx = Math.min(Math.max(x, rad), COLS - rad)
  return Math.hypot(x - cx, y - rad) - rad
}
const RING = 0.75
function classAt(x, y) {
  const d = sd(x, y)
  return d > 0 ? 'out' : d > -RING ? 'ring' : 'fill'
}
const QUAD = { 0: 0x20, 1: 0x2598, 2: 0x259d, 3: 0x2580, 4: 0x2596, 5: 0x258c, 6: 0x259e, 7: 0x259b, 8: 0x2597, 9: 0x259a, 10: 0x2590, 11: 0x259c, 12: 0x2584, 13: 0x2599, 14: 0x259f, 15: 0x2588 }

const words = []
for (let row = 0; row < ROWS; row++) for (let col = 0; col < COLS; col++) {
  const fill = hex(fillAt(col + 0.5))
  const er = row - 1, ec = col - emblemAt
  if (er >= 0 && er < EMBLEM.length && ec >= 0 && ec < EMBLEM[0].length) {
    const [cp, fg, bg] = EMBLEM[er][ec]
    words.push(cp, fg, bg ?? fill)
    continue
  }
  if (row === textRow && col >= verbAt && col < verbAt + VERB.length) { words.push(VERB.codePointAt(col - verbAt), SMOKE, fill); continue }
  if (row === textRow && col >= nameAt && col < nameAt + NAME.length) { words.push(NAME.codePointAt(col - nameAt), WHITE, fill); continue }
  if (row === textRow && col === verbAt + VERB.length) { words.push(0x20, fill, fill); continue }
  // quadrant subpixels, supersampled: TL, TR, BL, BR
  const subs = [[0, 0], [1, 0], [0, 1], [1, 1]].map(([i, j]) => {
    const tally = { out: 0, ring: 0, fill: 0 }
    for (let a = 0; a < 4; a++) for (let b = 0; b < 4; b++)
      tally[classAt(col + (i + (a + 0.5) / 4) / 2, row * 2 + j + (b + 0.5) / 4)]++
    // the ring wins any subpixel it covers a third of, so it stays continuous
    return tally.ring >= 5 ? 'ring' : tally.out >= tally.fill ? 'out' : 'fill'
  })
  const kinds = [...new Set(subs)]
  let fgKind, bgKind
  if (kinds.length === 1) { fgKind = kinds[0]; bgKind = kinds[0] }
  else if (kinds.includes('ring')) { fgKind = 'ring'; bgKind = kinds.includes('fill') && !kinds.includes('out') ? 'fill' : kinds.includes('out') && !kinds.includes('fill') ? 'out' : subs.filter(k => k === 'fill').length >= subs.filter(k => k === 'out').length ? 'fill' : 'out' }
  else { fgKind = 'fill'; bgKind = 'out' }
  const colorOf = k => (k === 'ring' ? hex(ringAt(col + 0.5)) : k === 'fill' ? fill : DEFAULT)
  let mask = 0
  subs.forEach((k, i) => { if (k === fgKind) mask |= 1 << i })
  if (fgKind === bgKind) words.push(0x20, colorOf(bgKind), colorOf(bgKind))
  else words.push(QUAD[mask], colorOf(fgKind), colorOf(bgKind))
}
const base64 = Buffer.from(new Uint32Array(words).buffer).toString('base64')
writeFileSync(
  new URL('../hooks/badge-cells.ts', import.meta.url),
  `// Generated by dev/make-badge.mjs from the Trusplex emblem: do not edit by hand.\n` +
    `// "${VERB} ${NAME}" as a Raster, ${COLS} x ${ROWS} cells.\n\n` +
    `export const BADGE_COLUMNS = ${COLS}\nexport const BADGE_ROWS = ${ROWS}\n` +
    `/** Where the name sits, for the bold overlay: row, column, text. */\n` +
    `export const BADGE_NAME = { row: ${textRow}, column: ${nameAt}, text: '${NAME}', background: '#${fillAt(nameAt + 0.5).map(v => Math.round(v).toString(16).padStart(2, '0')).join('')}' }\n` +
    `export const BADGE_CELLS =\n  '${base64}'\n`,
)
console.log(`badge: ${COLS}x${ROWS}`)
